import Head from "next/head";
import Layout from "../components/Layouts/Layout";
import dynamic from "next/dynamic";
import { useState } from "react";
const HeroSections = dynamic(() =>
  import("../components/SectionsPages/HeroSections")
);
const LatestNews = dynamic(() =>
  import("../components/SectionsPages/LatestNews")
);
const OurRoster = dynamic(() =>
  import("../components/SectionsPages/OurRoster")
);

export default function Home({ articles, rosters }) {
  const [showModal, setShowModal] = useState(false);
  return (
    <Layout>
      <Head>
        <title>Create Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSections />
      <LatestNews articles={articles} />
      <OurRoster rosters={rosters} />
    </Layout>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const resNews = await fetch(`http://localhost:4000/news`);
  const dataNews = await resNews.json();

  const resRosters = await fetch(`http://localhost:4000/rosters`);
  const dataRosters = await resRosters.json();

  // Pass data to the page via props
  return { props: { articles: dataNews, rosters: dataRosters } };
}
