import Head from 'next/head'
import Layout from '../components/Layouts/Layout'
import dynamic from 'next/dynamic'
const HeroSections= dynamic(()=>import("../components/SectionsPages/HeroSections"))
const LatestNews= dynamic(()=>import("../components/SectionsPages/LatestNews"))
const OurRoster= dynamic(()=>import("../components/SectionsPages/OurRoster"))
export default function Home() {
  return (
    <Layout bg='bg1'>
      <Head>
        <title>Create Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HeroSections/>
      <LatestNews/>
      <OurRoster/>
    </Layout>
  )
}
