import Head from 'next/head'
import LatestNews from '../components/SectionsPages/LatestNews'
import Layout from '../components/Layouts/Layout'
import OurRoster from '../components/SectionsPages/OurRoster'
import HeroSections from '../components/SectionsPages/HeroSections'
export default function Home() {
  return (
    <Layout bg='bg1'>
      <Head>
        <title>Create Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSections/>
      <LatestNews/>
      <OurRoster/>
    </Layout>
  )
}
